Fixed AttributeError and update dependency version
Error: AttributeError 'str' object does not have attribute author
File: bot.py line 16
Caused by wrongly calling "message.author.id" instead of properly calling "ctx.message.author.id"

File: requirements.txt
Update discord.py==1.2.5 to discord.py==1.3.3